language: objective-c
osx_image: xcode8.1
script: xcodebuild -project SabBar.xcodeproj -scheme SabBar -destination 'platform=iOS Simulator,name=iPhone 6' -enableCodeCoverage YES clean build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
